USE TEST 
--DATEADD (datepart , number , date )
--saat(HOUR),gün(DAY),yýl(YEAR) ekleme iþl
 DECLARE @TARIH AS DATETIME
 SET @TARIH ='2019-01-01 16:21:37'

 DECLARE @TARIH2 AS DATETIME
 SET @TARIH2=DATEADD(YEAR,16,@TARIH)
 SELECT @TARIH,@TARIH2

 --DATEDIFF ( datepart , startdate , enddate )FARKLARINI ALIYOR
 DECLARE @TARIH AS DATETIME
 SET @TARIH ='2019-01-01 16:21:37'

 DECLARE @TARIH2 AS DATETIME
 SET @TARIH2='2020-01-01 16:21:37'
 SELECT DATEDIFF(HOUR ,@TARIH,@TARIH2)

 --GETDATE() fonksiyonlarý anlýk anlýk tarih ve saati getirir.
 SELECT GETDATE()

 DECLARE @TARIH AS DATE
 SET @TARIH='1990-12-25'
 SELECT DATEDIFF(YEAR,@TARIH,GETDATE())



