--Alter kullanmamýzýn sebebi oluþturmuþ oldugumuz tablodaki sutünü silmemek için.
USE TEST
CREATE TABLE ISIMLER (ID INT IDENTITY(1,1),ISIM VARCHAR(20))

ALTER TABLE ISIMLER ADD ADRES VARCHAR(500)

ALTER TABLE ISIMLER DROP COLUMN ADRES

ALTER TABLE ISIMLER ALTER COLUMN ISIM VARCHAR(50)