--ROUND() VE RAND() FONKSIYONLAR ARASTRILMALI
--IF AND BETWEEN KOMUTLARI

		DECLARE @YAS INT,@DOGUMTARIHI DATETIME
		SET @YAS=DATEDIFF(YEAR,@DOGUMTARIHI,GETDATE())
		IF(@YAS <30)
		BEGIN 
		PRINT 'GENÇSÝZÝNÝZ'
		END
		IF(@YAS>=30 AND @YAS<=50)
		BEGIN
		PRINT 'ORTALAMA YAÞTASINIZ'
		END
		ELSE
		BEGIN
		PRINT 'YAÞLANMASINIZ'
		END

		declare @Sayac int=0;
		while @Sayac < 10 BEGIN PRINT @Sayac
		set @Sayac +=1;
		END
	
		DECLARE @YAS INT,@DOGUMTARIHI DATETIME,@Id int =0;
		
		while @Id<10 BEGIN
		
        SET @DOGUMTARIHI=(SELECT DOGUMTARIHI FROM KISILER WHERE ID =@Id)
	   set @YAS= (SELECT DATEDIFF(YEAR,@DOGUMTARIHI,GETDATE()))
	   
	   update KISILER SET YAS =@YAS WHERE ID=@Id

		set @Id+=1
		end
       
	    select AVG(YAS) FROM KISILER

		select *from KISILER where AD LIKE 'Z%';

		SELECT AD+' '+SOYAD AS Adý_Soyad  from KISILER WHERE ID BETWEEN 1 AND 2

		SELECT AD+' '+SOYAD AS Adý_Soyad  from KISILER WHERE ID NOT BETWEEN 1 AND  2 

		select * from KISILER WHERE YAS BETWEEN 20 AND 35 AND ID NOT IN (1);
