DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DÜNYA'

--SELECT SUBSTRING(@KELIME,9,5) -->Kelimeleri DÜNYA ALACAK
--SELECT LOWER(@KELIME) -->Kelimeleri tamamen küçük harfe çevirir.
SELECT UPPER(@KELIME) -->Kelimeleri tamamen büyük harfe çevirir.

--RIGHT LEFT
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DÜNYA'
select LEFT(@KELIME,4),RIGHT(@KELIME,4)

--LTRIM,RTRIM , TRIM
--Sagýndaki solundaki gereksiz boþluklarý temizler.
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='     Merhaba Dünya     '
SELECT LTRIM(@KELIME),RTRIM(@KELIME),TRIM(@KELIME),LTRIM(RTRIM(@KELIME))

--REPLACE -->Harf deðiþtirme iþlemleri yapýyor.
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DÜNYA'
SELECT REPLACE(@KELIME,'Ü','U')

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DÜNYA'
SELECT REPLACE(@KELIME,'DÜNYA','RAMAZAN')

--LEN -->KELÝME UZUNLUGUNU BULUYOR.
DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
SELECT LEN(@KELIME)

--STRING_SPLIT Kelime ayrý ayrý yazýyor.(Parçalama)
DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
SELECT
* FROM string_split(@KELIME,' ')

